"use client";
import { useState } from "react";
import { ArrowIcon, Badge, Button, ButtonLink, Card, Container, Eyebrow, SectionHeading } from "./index";
import "./gallery.css";
const sections = ["Overview", "Colors", "Typography", "Buttons", "Cards", "Layout"];
export function ComponentGallery() {
 const [active, setActive] = useState("Overview");
 const [variant, setVariant] = useState<"cream" | "electric" | "dark">("cream");
 const [size, setSize] = useState<"sm" | "md" | "lg">("md");
 const [disabled, setDisabled] = useState(false);
 const [count, setCount] = useState(0);
 const show = (name:string) => active === "Overview" || active === name;
 return <main className="ui-gallery">
  <aside><a className="ui-gallery-brand" href="/">trilha<span>Design library / 01</span></a><nav aria-label="Component categories">{sections.map(s=><button key={s} onClick={()=>setActive(s)} aria-current={active===s?"page":undefined}>{s}<span>↗</span></button>)}</nav><p>@trilha/ui<br />Shared by both sites.<br />Development only.</p></aside>
  <div className="ui-gallery-main"><header className="ui-gallery-intro"><Eyebrow>One family. Many paths.</Eyebrow><h1>Made to build<br /><em>together.</em></h1><p>The foundations and components behind Trilha. Real components, live interactions, one shared source.</p><Badge>v0.1 · Living library</Badge></header>
  {show("Colors") && <section><SectionHeading eyebrow="01 / Foundations">Our colors.</SectionHeading><div className="ui-gallery-swatches">{[["Ink","ink","#000928"],["Paper","paper","#fcfaf5"],["Button","button","#fffbf4"],["Mint","mint","#00d468"],["Electric","electric","#1c4ae5"],["Sky","sky","#a0b5ff"]].map(([name,token,hex])=><div key={token}><div style={{background:`var(--trilha-${token})`}}/><strong>{name}</strong><code>{hex}<br />--trilha-{token}</code></div>)}</div></section>}
  {show("Typography") && <section><SectionHeading eyebrow="02 / Typography" description="Poppins. A shared voice for headings, body copy, and controls.">De estudantes<br />para estudantes.</SectionHeading><p className="ui-gallery-body">A comunidade começa com gente por perto. Body copy stays generous, calm, and easy to read.</p><Eyebrow>Eyebrow / 11px / 600</Eyebrow><pre>{'<SectionHeading eyebrow="Nossa comunidade" description="Gente que aprende junto.">\n  Um novo começo.\n</SectionHeading>'}</pre></section>}
  {show("Buttons") && <section><SectionHeading eyebrow="03 / Interaction" description="Hover or focus to press. Click to test. Use Tab to inspect the focus ring.">A little push.</SectionHeading><div className="ui-gallery-controls"><label>Color<select value={variant} onChange={e=>setVariant(e.target.value as typeof variant)}><option value="cream">Cream</option><option value="electric">Electric</option><option value="dark">Dark</option></select></label><label>Size<select value={size} onChange={e=>setSize(e.target.value as typeof size)}><option>sm</option><option>md</option><option>lg</option></select></label><label><input type="checkbox" checked={disabled} onChange={e=>setDisabled(e.target.checked)}/> Disabled</label></div><div className="ui-gallery-stage"><Button variant={variant} size={size} disabled={disabled} onClick={()=>setCount(c=>c+1)}>Encontre seu caminho <ArrowIcon /></Button><span role="status">{count} clicks</span></div><div className="ui-gallery-row"><ButtonLink href="#library-layout">Link button <ArrowIcon direction="down" /></ButtonLink><Button disabled>Disabled</Button>{(["left","up","right","down","up-right"] as const).map(direction=><ArrowIcon key={direction} direction={direction}/>)}</div><pre>{`<Button variant="${variant}" size="${size}"${disabled?' disabled':''} onClick={handleClick}>\n  Encontre seu caminho <ArrowIcon />\n</Button>\n\n<ButtonLink href="/aulas">Acompanhe as aulas</ButtonLink>`}</pre></section>}
  {show("Cards") && <section><SectionHeading eyebrow="04 / Surfaces">Room for an idea.</SectionHeading><div className="ui-gallery-cards">{(["paper","mint","dark"] as const).map(tone=><Card tone={tone} key={tone}><Badge>Community</Badge><h3>Um começo<br />acompanhado.</h3><p>Gente por perto para aprender, experimentar e construir.</p></Card>)}</div><pre>{'<Card tone="mint">\n  <Badge>Community</Badge>\n  <h3>Um começo acompanhado.</h3>\n</Card>'}</pre></section>}
  {show("Layout") && <section id="library-layout"><SectionHeading eyebrow="05 / Layout" description="Content uses 80% width, capped at 1000px. On smaller screens it uses 92%. Heroes keep their own full-width composition.">Space to breathe.</SectionHeading><div className="ui-gallery-layout"><Container>Container / shared content width</Container></div><div className="ui-gallery-row">{[8,16,24,32,48,80].map(n=><div key={n}><div style={{width:n,height:16,background:'var(--trilha-electric)',marginBottom:8}}/><code>{n}px</code></div>)}</div><pre>{'import { Container, Button, SectionHeading } from "@trilha/ui";\nimport "@trilha/ui/styles.css";\n\n<Container>\n  <SectionHeading>Aprender juntos.</SectionHeading>\n</Container>'}</pre></section>}
  <footer>Trilha design system · Shared foundations, distinct experiences.</footer></div>
 </main>;
}
